<testsuites>
  <testsuite name="SampleProject.xUnit.dll" tests="7" skipped="1" failures="3" errors="0" time="0.0207116" timestamp="2024-11-14T07:12:46" hostname="DESKTOP" id="0" package="SampleProject.xUnit.dll">
    <properties />
    <testcase classname="SampleProject.xUnit.TestServiceTests" name="SkipTest" time="0.0010000">
      <skipped />
    </testcase>
    <testcase classname="SampleProject.NUnit.Attachment" name="AttachImage" time="0.0051982" />
    <testcase classname="SampleProject.xUnit.TestServiceTests" name="TestThrowingException" time="0.0053320">
      <failure type="failure" message="System.Exception : Pretty good exception">at SampleProject.TestService.GetException() in C:\Dev\LiquidTestReports\test\SampleProject\SampleProject\TestService.cs:line 19
   at SampleProject.xUnit.TestServiceTests.TestThrowingException() in C:\Dev\LiquidTestReports\test\SampleProject\SampleProject.Tests.xUnit\TestServiceTests.cs:line 54
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)</failure>
    </testcase>
    <testcase classname="SampleProject.xUnit.TestServiceTests" name="TestTheory(expected: True)" time="0.0055883" />
    <testcase classname="SampleProject.xUnit.TestServiceTests" name="TestTheory(expected: False)" time="0.0026951">
      <failure type="failure" message="Assert.Equal() Failure: Values differ&#xD;&#xA;Expected: False&#xD;&#xA;Actual:   True">at SampleProject.xUnit.TestServiceTests.TestTheory(Boolean expected) in C:\Dev\LiquidTestReports\test\SampleProject\SampleProject.Tests.xUnit\TestServiceTests.cs:line 29
   at InvokeStub_TestServiceTests.TestTheory(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)</failure>
    </testcase>
    <testcase classname="SampleProject.xUnit.TestServiceTests" name="PassingTest" time="0.0002885" />
    <testcase classname="SampleProject.xUnit.TestServiceTests" name="FailTest" time="0.0006095">
      <failure type="failure" message="Assert.True() Failure&#xD;&#xA;Expected: True&#xD;&#xA;Actual:   False">at SampleProject.xUnit.TestServiceTests.FailTest() in C:\Dev\LiquidTestReports\test\SampleProject\SampleProject.Tests.xUnit\TestServiceTests.cs:line 65
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)</failure>
    </testcase>
    <system-out>Not actually an attachment, just a placeholder to make the results the same.

Running SampleProject.Tests.xUnit tests

Running SampleProject.Tests.xUnit tests

Running SampleProject.Tests.xUnit tests

Running SampleProject.Tests.xUnit tests

Running SampleProject.Tests.xUnit tests
This test will fail


Test Framework Informational Messages:
[xUnit.net 00:00:00.00] xUnit.net VSTest Adapter v2.8.2+699d445a1a (64-bit .NET 8.0.11)
[xUnit.net 00:00:00.10]   Discovering: SampleProject.xUnit
[xUnit.net 00:00:00.16]   Discovered:  SampleProject.xUnit
[xUnit.net 00:00:00.16]   Starting:    SampleProject.xUnit
[xUnit.net 00:00:00.20]       Skipped
[xUnit.net 00:00:00.22]       System.Exception : Pretty good exception
[xUnit.net 00:00:00.22]       Stack Trace:
[xUnit.net 00:00:00.22]         C:\Dev\LiquidTestReports\test\SampleProject\SampleProject\TestService.cs(19,0): at SampleProject.TestService.GetException()
[xUnit.net 00:00:00.22]         C:\Dev\LiquidTestReports\test\SampleProject\SampleProject.Tests.xUnit\TestServiceTests.cs(54,0): at SampleProject.xUnit.TestServiceTests.TestThrowingException()
[xUnit.net 00:00:00.22]            at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
[xUnit.net 00:00:00.22]            at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
[xUnit.net 00:00:00.23]       Output:
[xUnit.net 00:00:00.23]         Running SampleProject.Tests.xUnit tests
[xUnit.net 00:00:00.23]       Assert.Equal() Failure: Values differ
[xUnit.net 00:00:00.23]       Expected: False
[xUnit.net 00:00:00.23]       Actual:   True
[xUnit.net 00:00:00.23]       Stack Trace:
[xUnit.net 00:00:00.23]         C:\Dev\LiquidTestReports\test\SampleProject\SampleProject.Tests.xUnit\TestServiceTests.cs(29,0): at SampleProject.xUnit.TestServiceTests.TestTheory(Boolean expected)
[xUnit.net 00:00:00.23]            at InvokeStub_TestServiceTests.TestTheory(Object, Span`1)
[xUnit.net 00:00:00.23]            at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
[xUnit.net 00:00:00.23]       Output:
[xUnit.net 00:00:00.23]         Running SampleProject.Tests.xUnit tests
[xUnit.net 00:00:00.23]       Assert.True() Failure
[xUnit.net 00:00:00.23]       Expected: True
[xUnit.net 00:00:00.23]       Actual:   False
[xUnit.net 00:00:00.23]       Stack Trace:
[xUnit.net 00:00:00.23]         C:\Dev\LiquidTestReports\test\SampleProject\SampleProject.Tests.xUnit\TestServiceTests.cs(65,0): at SampleProject.xUnit.TestServiceTests.FailTest()
[xUnit.net 00:00:00.23]            at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
[xUnit.net 00:00:00.23]            at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
[xUnit.net 00:00:00.23]       Output:
[xUnit.net 00:00:00.23]         Running SampleProject.Tests.xUnit tests
[xUnit.net 00:00:00.23]         This test will fail
[xUnit.net 00:00:00.24]   Finished:    SampleProject.xUnit
</system-out>
    <system-err>Warning - [xUnit.net 00:00:00.20]     SampleProject.xUnit.TestServiceTests.SkipTest [SKIP]
Error - [xUnit.net 00:00:00.22]     SampleProject.xUnit.TestServiceTests.TestThrowingException [FAIL]
Error - [xUnit.net 00:00:00.23]     SampleProject.xUnit.TestServiceTests.TestTheory(expected: False) [FAIL]
Error - [xUnit.net 00:00:00.23]     SampleProject.xUnit.TestServiceTests.FailTest [FAIL]
</system-err>
  </testsuite>
</testsuites>