<testsuites>
  <testsuite name="SampleProject.xUnit.dll" tests="6" skipped="1" failures="3" errors="0" time="0.010323700000000002" timestamp="2021-05-03T04:25:44" hostname="DESKTOP-1B2SI9I" id="0" package="SampleProject.xUnit.dll">
    <properties />
    <testcase classname="SampleProject.xUnit.TestServiceTests" name="SampleProject.xUnit.TestServiceTests.TestTheory(expected: True)" time="0.0051887" />
    <testcase classname="SampleProject.xUnit.TestServiceTests" name="SampleProject.xUnit.TestServiceTests.TestTheory(expected: False)" time="0.0027797">
      <failure type="failure" message="Assert.Equal() Failure&#xD;&#xA;Expected: False&#xD;&#xA;Actual:   True">at SampleProject.xUnit.TestServiceTests.TestTheory(Boolean expected) in C:\Dev\LiquidTestReports\test\SampleProject\SampleProject.Tests.xUnit\TestServiceTests.cs:line 29</failure>
    </testcase>
    <testcase classname="SampleProject.xUnit.TestServiceTests" name="SampleProject.xUnit.TestServiceTests.SkipTest" time="0.0010000">
      <skipped />
    </testcase>
    <testcase classname="SampleProject.xUnit.TestServiceTests" name="SampleProject.xUnit.TestServiceTests.TestThrowingException" time="0.0004952">
      <failure type="failure" message="System.Exception : Pretty good exception">at SampleProject.TestService.GetException() in C:\Dev\LiquidTestReports\test\SampleProject\SampleProject\TestService.cs:line 19
   at SampleProject.xUnit.TestServiceTests.TestThrowingException() in C:\Dev\LiquidTestReports\test\SampleProject\SampleProject.Tests.xUnit\TestServiceTests.cs:line 54</failure>
    </testcase>
    <testcase classname="SampleProject.xUnit.TestServiceTests" name="SampleProject.xUnit.TestServiceTests.PassingTest" time="0.0003146" />
    <testcase classname="SampleProject.xUnit.TestServiceTests" name="SampleProject.xUnit.TestServiceTests.FailTest" time="0.0005455">
      <failure type="failure" message="Assert.True() Failure&#xD;&#xA;Expected: True&#xD;&#xA;Actual:   False">at SampleProject.xUnit.TestServiceTests.FailTest() in C:\Dev\LiquidTestReports\test\SampleProject\SampleProject.Tests.xUnit\TestServiceTests.cs:line 65</failure>
    </testcase>
    <system-out>Running SampleProject.Tests.xUnit tests

Running SampleProject.Tests.xUnit tests

Skipped
Running SampleProject.Tests.xUnit tests

Running SampleProject.Tests.xUnit tests

Running SampleProject.Tests.xUnit tests
This test will fail


Test Framework Informational Messages:
[xUnit.net 00:00:00.00] xUnit.net VSTest Adapter v2.4.3+1b45f5407b (64-bit .NET Core 3.1.14)
[xUnit.net 00:00:00.41]   Discovering: SampleProject.xUnit
[xUnit.net 00:00:00.47]   Discovered:  SampleProject.xUnit
[xUnit.net 00:00:00.47]   Starting:    SampleProject.xUnit
[xUnit.net 00:00:00.56]       Assert.Equal() Failure
[xUnit.net 00:00:00.56]       Expected: False
[xUnit.net 00:00:00.56]       Actual:   True
[xUnit.net 00:00:00.56]       Stack Trace:
[xUnit.net 00:00:00.56]         C:\Dev\LiquidTestReports\test\SampleProject\SampleProject.Tests.xUnit\TestServiceTests.cs(29,0): at SampleProject.xUnit.TestServiceTests.TestTheory(Boolean expected)
[xUnit.net 00:00:00.56]       Output:
[xUnit.net 00:00:00.56]         Running SampleProject.Tests.xUnit tests
[xUnit.net 00:00:00.56]       Skipped
[xUnit.net 00:00:00.56]       System.Exception : Pretty good exception
[xUnit.net 00:00:00.56]       Stack Trace:
[xUnit.net 00:00:00.56]         C:\Dev\LiquidTestReports\test\SampleProject\SampleProject\TestService.cs(19,0): at SampleProject.TestService.GetException()
[xUnit.net 00:00:00.56]         C:\Dev\LiquidTestReports\test\SampleProject\SampleProject.Tests.xUnit\TestServiceTests.cs(54,0): at SampleProject.xUnit.TestServiceTests.TestThrowingException()
[xUnit.net 00:00:00.56]       Output:
[xUnit.net 00:00:00.56]         Running SampleProject.Tests.xUnit tests
[xUnit.net 00:00:00.56]       Assert.True() Failure
[xUnit.net 00:00:00.56]       Expected: True
[xUnit.net 00:00:00.56]       Actual:   False
[xUnit.net 00:00:00.56]       Stack Trace:
[xUnit.net 00:00:00.56]         C:\Dev\LiquidTestReports\test\SampleProject\SampleProject.Tests.xUnit\TestServiceTests.cs(65,0): at SampleProject.xUnit.TestServiceTests.FailTest()
[xUnit.net 00:00:00.56]       Output:
[xUnit.net 00:00:00.56]         Running SampleProject.Tests.xUnit tests
[xUnit.net 00:00:00.56]         This test will fail
[xUnit.net 00:00:00.57]   Finished:    SampleProject.xUnit
</system-out>
    <system-err>Error - [xUnit.net 00:00:00.56]     SampleProject.xUnit.TestServiceTests.TestTheory(expected: False) [FAIL]
Warning - [xUnit.net 00:00:00.56]     SampleProject.xUnit.TestServiceTests.SkipTest [SKIP]
Error - [xUnit.net 00:00:00.56]     SampleProject.xUnit.TestServiceTests.TestThrowingException [FAIL]
Error - [xUnit.net 00:00:00.56]     SampleProject.xUnit.TestServiceTests.FailTest [FAIL]
</system-err>
  </testsuite>
</testsuites>